### ISSUE TITLE
Can't mkdir parents for /var/run/user/1000/.dbus-proxy/: No such file or directory

### ISSUE THREAD

**Issue by edwargix** [fosero/flatpak-overlay#13] opened 2018-01-03 20:09 UTC
Hello,

I installed flatpak and have installed several applications. There was no issue there. However, when I try to run any application, ie `flatpak run ...`, I get the error message `Can't mkdir parents for /var/run/user/1000/.dbus-proxy/: No such file or directory`.

After some browsing, I found the solution here: https://github.com/flatpak/flatpak/issues/534. By running the command, `XDG_RUNTIME_DIR=/run/user/1000 flatpak run ...` the application runs fine. Do you have any idea why this problem eixsts, and whether there is a more elegant solution?

Thanks in advance.

BTW, I am using OpenRC

**Comment by fosero** [comment] 2018-01-03 20:29
I assume you mean `XDG_RUNTIME_DIR=/var/run/user/1000 ...`?

I don't use openrc anymore, so can't be of much help here. You should inform the Gentoo openrc maintainers of this issue and ask if they can set it for you.

I'm going to close this as this is outside the scope of the repo. The flatpak ebuild shouldn't be setting environment vars for you.

I would appreciate it if you could drop the Gentoo bug number here if you decide to file one.

**Closed as completed by fosero** 2018-01-03 20:29 UTC
Labels: invalid

**Comment by ald0n** [comment] 2018-08-30 20:18
Can confirm that, faced the same issue. Used that as a workaround
>By running the command, XDG_RUNTIME_DIR=/run/user/1000 flatpak run ... the application runs fine.

, but not /var/run(which actually was already set in env) like you mention.

**Comment by ZeroPointEnergy** [comment] 2018-09-25 09:25
Shouldn't this be kept open until it is fixed wherever the bug may be?

Because I just ran into this and it took me quite a while to find the workaround here because I wasn't thinking about looking into the closed issues if the issue still exists.

**Comment by ZeroPointEnergy** [comment] 2018-09-25 19:52
I attempted to fix this upstream. For reference: https://github.com/flatpak/flatpak/pull/2137

**Comment by edwargix** [comment] 2018-09-28 14:03
Thank you @ZeroPointEnergy. I agree this issue should be reopened, but I unfortunately can't make that decision.

**Comment by fosero** [comment] 2018-10-01 10:19
Reason I don't keep this open: it is not a bug in this repo. It is upstream. If there is nothing upstream, there is nothing for me to track here. I just provide the ebuilds as-is for general use, the support pretty much ends there.

Anyway, I added the patch to 1.0.2-r1, thanks for figuring this out @ZeroPointEnergy :+1:

**Comment by ZeroPointEnergy** [comment] 2018-10-01 18:01
Thanks for adding the patch. The PR seems to be merged now so the next upstream release will hopefully work out of the box for openrc as well.
